{% set version = "0.8.5" %}
{% set name="structToolbox" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://github.com/computational-metabolomics/{{ name|lower }}/archive/v{{ version|lower }}.tar.gz'
  md5: 7cb8483e38c8f278ee2e0e77e597061e 
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - icu ==64.2
    - tbb <=2020.2
    - r-base ==3.6.1
    - r-ggplot2 ==3.2.1
    - r-gridextra =2.3
    - r-missforest ==1.4
    - r-ggthemes ==4.2.0
    - r-pls ==2.7_1
    - r-sp ==1.3_1
    - r-scales ==1.1.0
    - r-car ==3.0_3
    - r-reshape2
    - r-agricolae ==1.3_1
    - r-openxlsx
    - r-knitr ==1.26
    - r-rmarkdown ==1.17
    - r-captioner ==2.2.3
    - r-emmeans ==1.4.2
    - r-lmertest ==3.1_0
    - r-lme4
    - r-nlme
    - r-mvtnorm
    - r-ggdendro
    - r-rtsne
    - r-stringi ==1.4.3
    - bioconductor-impute ==1.60.0
    - bioconductor-pcaMethods ==1.78.0
    - bioconductor-sbcms >=0.99.1
    - bioconductor-struct ==0.4.1
    - bioconductor-pmp ==0.2.4
  run:
    - icu ==64.2
    - tbb <=2020.2
    - r-base ==3.6.1
    - r-ggplot2 ==3.2.1
    - r-gridextra =2.3
    - r-missforest ==1.4
    - r-ggthemes ==4.2.0
    - r-pls ==2.7_1
    - r-sp ==1.3_1
    - r-scales ==1.1.0
    - r-car ==3.0_3
    - r-reshape2
    - r-agricolae ==1.3_1
    - r-openxlsx
    - r-knitr ==1.26
    - r-rmarkdown ==1.17
    - r-captioner ==2.2.3
    - r-emmeans ==1.4.2
    - r-lmertest ==3.1_0
    - r-lme4
    - r-nlme
    - r-mvtnorm
    - r-ggdendro
    - r-rtsne
    - r-stringi ==1.4.3
    - bioconductor-impute ==1.60.0
    - bioconductor-pcaMethods ==1.78.0
    - bioconductor-sbcms >=0.99.1
    - bioconductor-struct ==0.4.1
    - bioconductor-pmp ==0.2.4
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://github.com/computational-metabolomics/structToolbox'
  license: 'GPL (>= 2)'
  summary: 'Extends the class templates provided by the struct package to provide methods for training PCA, PLS models with cross-validation, permutation testing etc.'

