{% set version = "1.3.1" %}
{% set name="structToolbox" %}
{% set bioc = "3.13" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
  md5: 1746266dc3aea209d1160259d2af22c2  
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - pandoc
    - icu
    - r-base >4.0
    - r-ggplot2
    - r-gridExtra
    - r-missforest
    - r-ggthemes
    - r-pls
    - r-sp
    - r-scales
    - r-car
    - r-reshape2
    - r-agricolae
    - r-openxlsx
    - r-knitr
    - r-rmarkdown
    - r-captioner
    - r-emmeans
    - r-lmertest
    - r-lme4
    - r-nlme
    - r-mvtnorm
    - r-ggdendro
    - r-rtsne
    - r-stringi
    - bioconductor-impute
    - bioconductor-pcaMethods
    - bioconductor-struct
    - bioconductor-pmp
  run:
    - pandoc
    - icu
    - r-base >4.0
    - r-ggplot2
    - r-gridExtra
    - r-missforest
    - r-ggthemes
    - r-pls
    - r-sp
    - r-scales
    - r-car
    - r-reshape2
    - r-agricolae
    - r-openxlsx
    - r-knitr
    - r-rmarkdown
    - r-captioner
    - r-emmeans
    - r-lmertest
    - r-lme4
    - r-nlme
    - r-mvtnorm
    - r-ggdendro
    - r-rtsne
    - r-stringi
    - bioconductor-impute
    - bioconductor-pcaMethods
    - bioconductor-struct
    - bioconductor-pmp
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Extends the class templates provided by the struct package to provide methods for training PCA, PLS models with cross-validation, permutation testing etc.'

