{% set version="0.1.2" %}
{% set name="xlsxbuilder" %}

package:
  name: 'r-{{name|lower}}'
  version: '{{ version }}'
source:
  url: 
    - 'https://github.com/computational-metabolomics/{{ name|lower }}/archive/v{{ version|lower }}.tar.gz'
  md5: 5586e910dd0e0ac134b750202dcbe9f2
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'r-base ==3.6.1'
    - r-openxlsx
  run:
    - 'r-base ==3.6.1'
    - r-openxlsx
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://github.com/computational-metabolomics/{{ name|lower }}'
  license: 'GPL (>= 2)'
  summary: 'Easily formatted excel outputs.'
