{% set version="0.1.4" %}
{% set name="xlsxbuilder" %}

package:
  name: 'r-{{name|lower}}'
  version: '{{ version }}'
source:
  url: 
    - 'https://github.com/computational-metabolomics/{{ name|lower }}/archive/v{{ version|lower }}.tar.gz'
  md5: fab06db4a481a6e31d6e1950592e49e0
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'r-base >=4.2,<4.3'
    - r-openxlsx
  run:
    - 'r-base >=4.2,<4.3'
    - r-openxlsx
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://github.com/computational-metabolomics/{{ name|lower }}'
  license: 'GPL (>= 2)'
  summary: 'Easily formatted excel outputs.'
