{% set version="0.1.0" %}
{% set name="amimspy" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://test-files.pythonhosted.org/packages/b6/4e/ad0a61dace14a9e16e6501c4637fc1e230da89051ee8b8307dcb5e8e9d0e/amimspy-0.1.0.tar.gz
  sha256: '73a64c643d8262517e3648439740c24d3a96f64c9ed4b75417561efe64ab8536'

build:
  noarch: python
  number: 0
  entry_points:
    - beamspy = beamspy.__main__:main
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - python >3.7
    - pip
  run:
    - python >3.7
    - dimspy ==2.0.0

test:
  imports:
    - amimspy
  commands:
    - amimspy --help

about:
  home: https://github.com/computational-metabolomics/amimspy
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: LICENSE
  summary: Python package for processing acoustic mist ionization mass spectrometry-based metabolomics and lipidomics data

extra:
  recipe-maintainers:
    - RJMW
