{% set version = "1.3.1" %}
{% set name = "struct" %}
{% set bioc = "3.13" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
  md5: 200623f38fa71f08198d6e9e20ff22db
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: testthat, rstudioapi, rmarkdown, covr, BiocStyle, openxlsx, ggplot2, magick
requirements:
  host:
    - 'bioconductor-s4vectors >=0.28.0,<0.29.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - 'r-base >4.0,<4.1'
    - r-knitr
    - r-ontologyindex
  run:
    - 'bioconductor-s4vectors >=0.28.0,<0.29.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - 'r-base >4.0,<4.1'
    - r-knitr
    - r-ontologyindex
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Statistics in R Using Class-based Templates'
  description: 'Defines and includes a set of class-based templates for developing and implementing data processing and analysis workflows, with a strong emphasis on statistics and machine learning. The templates can be used and where needed extended to ''wrap'' tools and methods from other packages into a common standardised structure to allow for effective and fast integration. Model objects can be combined into sequences, and sequences nested in iterators using overloaded operators to simplify and improve readability of the code. STATistics Ontology (STATO) has been integrated and implemented to provide standardised definitions for methods, inputs and outputs wrapped using the class-based templates.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
